trigger:
- none
pool:
  name: batch3-cicd-pool
  vmImage: server1

variables:
 - group: "java-vars"
steps:

- task: Bash@3
  displayName: "build artifacts"
  inputs:
    targetType: 'inline'
    script: |
      mvn clean package
    failOnStderr: true

- task: Bash@3
  displayName: "sonar scanner"
  env:
    SONAR_TOKEN: $(SONAR_TOKEN)
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      	echo "Executing sonar cli"
      	sonar-scanner \
      	-Dsonar.projectKey="dvsbatch3-org1_dotnetcore"  \
      	-Dsonar.sources="./target/"   \
      	-Dsonar.host.url="https://sonarcloud.io" \
      	-Dsonar.branch.name="master" \
      	-Dsonar.token=$(SONAR_TOKEN) \
      	-Dsonar.organization="dvsbatch3-org1"
    failOnStderr: true
